sudo: false
language: java
jdk:
- oraclejdk8
- oraclejdk9
notifications:
  email:
  - pmlopes@gmail.com
env:
  global:
  - secure: RW98CXIpIhMm17UFI7NsFZmmpPOe48IT2R1vKonLkG37av6wTOrVjLZlpihTrIGUuyJsIvrOrM2tybzT+Cq2o1/h4P9XxufzUdyHabh4Ppk1cSQzfEL/vKwBU8HFgUwsuRKVjhowKUXAwKhDtU+oorJWiFqrv1JC/boJOwT71qOZqPdu6A5s7+ubcdUCimwFI0XNGzBZ+phtcdE4dVC5l176/sJVoCGaefG+cZxjCU6AvWnVcPz9POZvtpHvZU1pE26LKgMIiPPgDdxg1oRpcOVPSTKw9Zu9lI1VqfrBj/6k4TsyEWujFtVO9RS0EeMjw6N9diIocdajAhMcSlihytMrBK8DTShnNCaSwxEaqFZUtiY0ZOvYxo9RU0QBGaADvMz5qC701Kmq0eJvDCjdjA37hWeD/wSru3czrsn46Ub3TjqAAOjQCFhcN3wVrZ0r586g1YwueuXKlAQwBEY5k3KP6NqUInxiYW7GYYOsPFxBrPomZSvzdo3GE8pLxChJvuBONtEKnNkmBjFTRTgrNwr3Jw2TlJP1lZQ96YmVM3Hz8fzWJdaTyMgzjpx8TrU17hzfPH27zibP3fdiGZRWtRtCDMmC3wpC5S37hiDUn42laDAAghGKA0K4c2xbUz73L0r9jZaiXYShxqA6G/e9PNDwAYDxflf3ysb1Vf6hVU0=
  - secure: w5bMX1j/wDNLbaqDXFhMDtzyu4Th32OOQ7K2gQnppxb+lTdy3iNjzjrDkGTnM69Oe+AsXo68LiER0kRkZp7LgUrwtGrQ9J6JxUzXhqiaK9vvIF8OQ40DfvZHQwWnF23gjqyNGHpD0gPwbgjAqH3Snz96VVD5I6TbcJpHtj6VAzECmsikfpwlSiWOFXjT/6nRPYWf51lfZMyg1R9MhV4CoEIugmmM0F/bTDBwNG5gxakCwOqQ1WqbzphzxTNfyTu9LJSUXPMx6kWk2lZNUwgUjKIVlAOGbYp6H2DWdBfGxey2rj9VQBizFc7uZAeX7GG45pcRUqOKyutQQS7DBLCSZnceHe1ssZ5FGhY3x79nYfRm85wIPDkNXdUnZR8hxMLNBejZ3PpOx1piz7b8AkTUM357BuMSY7k4E/rvmeJ5E8H5J1TwUiCRM1y6/8Rvm2CfiMLXN+gD3lVhqPbALTc+D8fdIZ9lj7x6HKLYCwevwhbEZ6yFcASGWK7svFWFRzYD3gZ3ukJ+jpdO6+djysKTKjAVZ4FYWQrUPSetFDo93lCmIE1WToyi40CK1vcz6SdxU8Cawtz1cDvaSxYpMOqJsePL/oIewPtWvxmcsVnk0sTQdZM2yRHEJZBp6PrnycVEYDwiCsFyepEqKeD4uJlVyEOtlLGpXMSPWCKQBYdOOfM=
after_success:
- '[[ "${TRAVIS_BRANCH}" = "develop" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]] && mvn --setings settings.xml deploy -DskipTests -B || true'
