# Project information
site_name: EcmaScript for Eclipse Vert.x
site_description: A Modern EcmaScript runtime for Eclipse Vert.x
site_author: Paulo Lopes
site_url: https://reactiverse.io/es4x/

# Repository
repo_name: reactiverse/es4x
repo_url: https://github.com/reactiverse/es4x
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 Paulo Lopes'

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: 'deep purple'
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: https://www.jetdrone.xyz
    - type: github-alt
      link: https://github.com/pmlopes
    - type: twitter
      link: https://twitter.com/pml0pes
    - type: linkedin
      link: https://linkedin.com/in/pmlopes

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - ES4X: index.md
  # Menu items
  - Getting started:
      - Installing: start/install.md
      - Hello World: start/hello-world.md
      - Generator: start/generator.md
      - FAQ: start/FAQ.md
  - Guide:
      - Running: guide/run.md
      - Debugging: guide/debug.md
      - Packaging: guide/package.md
      - Shell: guide/shell.md
  - API reference:
      - "@vertx": api/vertx.md
      - "@reactiverse": api/reactiverse.md
  - Advanced topics:
      - Asynchronous Programming: advanced/async-programming.md
      - Workers: advanced/worker.md
      - GraalVM: advanced/graalvm.md
  - Resources: resources/index.md
  - Contributing: contributing.md
  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
